UI for customer rental
SeanBlackford37/Music-Store-Rehearsal-Space pull request #63
Opened 2021-04-12 21:56 UTC by SeanBlackford37

2021-04-13 00:57 UTC, pseudaimonia requested changes
Hey Sean, I think there's going to be an issue with canceling item rentals, if the transactions are added to the front of the list each time. Currently, the cancel function iterates backwards through the list to find the most recent transaction. Instead, it would probably be easier to change item return to iterate backwards, too, and add the transaction to the end of the list when renting. Otherwise, everything else looks good.

2021-04-13 19:29 UTC, pseudaimonia approved these changes

2021-04-14 13:48 UTC, mziegler611 approved these changes

2021-04-14 13:59 UTC, dberman5 approved these changes

2021-04-14 14:01 UTC, merged